apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ko7r43l-2-go
  janus-idp.io/tekton: ko7r43l-2-go
  backstage.io/kubernetes-id: ko7r43l-2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ko7r43l-2-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
